### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by danharbor95** [ark-lang/ark-syntax-highlighting#2]
Can we have atom highlighting, this would be cool. Thanks

**Comment by MovingtoMars** [comment]
Yeah, I'm planning on doing this, as I now use atom myself.

**Comment by danharbor95** [comment]
Neat, give me a ping on this when it is done :3

**Comment by MovingtoMars** [comment]
@danharbor95 https://atom.io/packages/language-ark

It needs quite a bit more work though.

**Comment by danharbor95** [comment]
@MovingtoMars Great job, thanks! :)
